
name: workflow
on:
  push:
    branches:
      - master
jobs:
  jest:
    if: contains(github.event.head_commit.message, '[CI SKIP]') == false && contains(github.event.head_commit.message, '[CI AUTO]') == false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install package
        run: npm install
      - name: Jest
        run: |
          node --version
          npm --version
          npm test